version: "3.9"

services:

  token-api:
    image: hubviwe/jwtauthentication.token.api:1.0.0
    build:
        context: src/
        dockerfile: API/Dockerfile
    environment:
        ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 5161:80
      - 7161:443
