version: "3.9"

services:

  token-api:
    image: hubviwe/jwtauthentication.token.api:1.0.5
    container_name: token-api
    build:
        context: src/
        dockerfile: API/Dockerfile
    environment:
        ASPNETCORE_ENVIRONMENT: Docker
    ports:
      - 5161:80
    depends_on:
      - postgres
    restart: on-failure

  postgres:
    image: postgres:13-alpine
    hostname: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: "user"
        POSTGRES_PASSWORD: "pass"
            
  mongo:
    image: mongo
    hostname: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example


  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
