version: "3.9"

services:

  token-api:
    image: hubviwe/jwtauthentication.token.api:dev
    container_name: token-api
    build:
        context: src/
        dockerfile: API/Dockerfile
    environment:
        ASPNETCORE_ENVIRONMENT: Docker
    ports:
      - 5161:80
    depends_on:
      - postgres

  postgres:
    image: "postgres:13-alpine"
    hostname: "postgres"
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: "user"
        POSTGRES_PASSWORD: "pass"
