version: "3.9"
name: jwt-authentication

services:

  token-api:
    image: hubviwe/jwtauthentication.token.api:1.0.8
    container_name: token-api
    restart: on-failure
    build:
        context: src/
        dockerfile: API/Dockerfile
    environment:
        ASPNETCORE_ENVIRONMENT: Docker
    ports:
      - 5161:80
    depends_on:
      - mongo
      - jaeger

  mongo:
    image: mongo
    hostname: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  jaeger:
    image: jaegertracing/all-in-one
    hostname: jaeger
    container_name: jaeger
    ports:
      - "6831:6831/udp" # accepts jaeger.thrift over compact thrift protocol
      - "16686:16686" # ui
