version: "3.9"
name: jwt-authentication

services:
            
  mongo:
    image: mongo
    hostname: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  jaeger:
    image: jaegertracing/all-in-one
    hostname: jaeger
    container_name: jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - 16686:16686 # jaeger ui
      - 4317:4317 # accept OpenTelemetry Protocol (OTLP) over gRPC
      - 4318:4318 # accept OpenTelemetry Protocol (OTLP) over HTTP
